[tool.pytest.ini_options]
minversion = "7.1.0"
addopts = "-ra"
testpaths = [
    "tests"
]
log_cli = false
log_cli_level = "DEBUG"
log_cli_format = "%(asctime)s [%(levelname)8s] %(message)s (%(filename)s:%(lineno)s)"

# log_file = "pytest.log"
# log_file_level = "DEBUG"
# log_file_format = "%(asctime)s [%(levelname)8s] %(message)s (%(filename)s:%(lineno)s)"
# log_file_date_format="%Y-%m-%d %H:%M:%S"

[tool.mypy]
python_version = "3.10"
files = [
    "module1/**/*.py",
    "tests/**/*.py"
]
show_error_codes = true

[tool.black]
line-length = 88
target-version = ["py310"]
include = '\.pyi?$'

[tool.isort]
py_version = 3
# Set `profile = "black"` for `black` compatibility.
# See: https://pycqa.github.io/isort/docs/configuration/black_compatibility.html
profile = "black"
src_paths = [
    "module1",
    "tests"
]
skip_gitignore = true
known_local_folder = ["module1"]
